[binaries]
c       = 'emcc'
cpp     = 'em++'
ar      = 'emar'
strip   = 'emstrip'
# If emsdk is not on PATH, provide an absolute path, e.g.:
# cpp = '/opt/homebrew/opt/emscripten/libexec/upstream/emscripten/em++'

[host_machine]
system     = 'emscripten'
cpu_family = 'wasm32'
cpu        = 'wasm32'
endian     = 'little'

[built-in options]
# Optimise for size when targeting the web
cpp_std    = 'c++20'
